executor: slurm
scheduler: greedy
default-resources:
    slurm_account: jingke.weng
    slurm_partition: short
    runtime: 2880
    threads: 1
    mem: 2gb
set-resources:
    trimmomatic_parallel:
        mem: 10gb
        threads: 4
    fastqc_before_trim:
        mem: 4gb
        threads: 4
    fastqc_after_trim:
        mem: 4gb
        threads: 4
    multiqc_after_trim:
        mem: 4gb
    trinity_inchworm_chrysalis:
        slurm_partition: long
        runtime: 7200
        mem: 384gb
        threads: 16
    trinity_butterfly_parallel:
        threads: 2
        mem: 4gb
        runtime: 120
    trinity_butterfly_parallel_merge:
        mem: 10gb
    trinity_final:
        slurm_partition: long
        runtime: 7200
        mem: 256gb
        threads: 16
    busco:
        mem: 10gb
        threads: 4
    transdecoder_predict:
        mem: 10gb
    download_sprot:
        mem: 4gb
    rfam_parallel:
        mem: 8gb
        threads: 4
    pfam_parallel:
        threads: 4
    sprot_blastp_parallel:
        mem: 4gb
        threads: 4
    signalp_parallel:
        mem: 8gb
    kallisto:
        mem: 16gb
        threads: 8    
    annotated_fasta:
        mem: 4gb
restart-times: 2
latency-wait: 60
jobs: 1000
rerun-incomplete: True
conda-frontend: conda
use-conda: True
